version: '3.8'

services:
  ollama:
    image: ollama/ollama:0.5.11
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_storage:/root/.ollama
    networks:
      - rag

  qdrant:
    image: qdrant/qdrant:v1.13.3
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    networks:
      - rag

  anythingllm:
    image: mintplexlabs/anythingllm:1.4.0
    container_name: anythingllm
    ports:
    - "3001:3001"
    environment:
      - STORAGE_DIR=/app/server/storage
      - JWT_SECRET="make this a large list of random numbers and letters 20+"
      - LLM_PROVIDER=ollama
      - OLLAMA_BASE_PATH=http://ollama:11434
      - OLLAMA_MODEL_PREF=hf.co/bartowski/Qwen2.5-3B-Instruct-GGUF:Q4_K_M
      - OLLAMA_MODEL_TOKEN_LIMIT=4096
      - EMBEDDING_ENGINE=ollama
      - EMBEDDING_BASE_PATH=http://ollama:11434
      - EMBEDDING_MODEL_PREF=bge-m3:567m-fp16
      - EMBEDDING_MODEL_MAX_CHUNK_LENGTH=8192
      - VECTOR_DB=qdrant
      - QDRANT_ENDPOINT=http://qdrant:6333
      - PASSWORDMINCHAR=8
    volumes:
      - anythingllm_storage:/app/server/storage
    depends_on:
      - ollama
      - qdrant
    networks:
      - rag

volumes:
  ollama_storage:
  qdrant_storage:
  anythingllm_storage:

networks:
  rag:
    driver: bridge
